#!/usr/bin/env bash
# Medical-AI 云服务器一键部署脚本（V4，免备案 + nip.io + Caddy 自动 HTTPS）
#
# 在云服务器（Ubuntu 22.04 推荐）上以 root 或 sudo 用户身份运行：
#   cd Medical-AI && bash deploy/setup.sh
#
# 这个脚本做：
#   1. 检测/安装 Docker（如果还没装）
#   2. 自动探测服务器公网 IPv4 → 生成 nip.io 域名
#   3. 交互式生成强随机的 ADMIN_TOKEN 和 POSTGRES_PASSWORD
#   4. 写出 .env（仅本机；.gitignore 已排除）
#   5. docker compose -f docker-compose.prod.yml up -d --build
#   6. 等服务起来，打印最终访问 URL
#
# 跑完后医生可访问 https://<ip-dashed>.nip.io，管理员可访问
# https://<ip-dashed>.nip.io/admin 输 ADMIN_TOKEN 登录下载数据。

set -euo pipefail

# --- 颜色 ---------------------------------------------------------------
RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; BLUE=$'\033[34m'; BOLD=$'\033[1m'; RESET=$'\033[0m'
log()  { echo "${BLUE}[setup]${RESET} $*"; }
warn() { echo "${YELLOW}[setup]${RESET} $*"; }
fail() { echo "${RED}[setup]${RESET} $*" >&2; exit 1; }
ok()   { echo "${GREEN}[setup]${RESET} $*"; }

# --- 0. 必须在 Medical-AI 仓库根目录运行 -------------------------------
if [ ! -f docker-compose.prod.yml ] || [ ! -d deploy ]; then
  fail "请在 Medical-AI 仓库根目录运行：  cd Medical-AI && bash deploy/setup.sh"
fi

# --- 1. 检查/安装 Docker ----------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  log "未检测到 Docker，自动安装中…（首次约 1-2 分钟）"
  curl -fsSL https://get.docker.com | sh
  ok "Docker 安装完成"
else
  ok "Docker 已安装：$(docker --version)"
fi

# Compose v2 是 docker 子命令；旧版 docker-compose 不支持。
if ! docker compose version >/dev/null 2>&1; then
  fail "找不到 docker compose v2。请升级 Docker 到较新版本（get.docker.com）。"
fi

# --- 2. 探测公网 IPv4 → 生成 nip.io 域名 ------------------------------
log "探测服务器公网 IPv4…"
PUBLIC_IP="$(curl -s --max-time 5 https://api.ipify.org || true)"
if [ -z "${PUBLIC_IP}" ]; then
  PUBLIC_IP="$(curl -s --max-time 5 https://ifconfig.me || true)"
fi
if [ -z "${PUBLIC_IP}" ]; then
  read -rp "无法自动检测公网 IP，请手动输入本服务器的公网 IPv4: " PUBLIC_IP
fi
[ -n "${PUBLIC_IP}" ] || fail "公网 IP 必填"
ok "服务器公网 IP：${PUBLIC_IP}"

NIP_DOMAIN="${PUBLIC_IP//./-}.nip.io"
ok "生成访问域名：${NIP_DOMAIN}"

read -rp "用这个 nip.io 域名？回车确认，或输入你已备好的真实域名: " CUSTOM_DOMAIN
SITE_DOMAIN="${CUSTOM_DOMAIN:-$NIP_DOMAIN}"
ok "将申请 Let's Encrypt 证书给：${SITE_DOMAIN}"

# --- 3. 生成强随机 ADMIN_TOKEN / POSTGRES_PASSWORD ---------------------
gen_token() {
  # 32 字节十六进制 = 64 字符，足够强
  python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null \
    || openssl rand -hex 32 2>/dev/null \
    || head -c 32 /dev/urandom | xxd -p -c 32
}

ADMIN_TOKEN_DEFAULT="$(gen_token)"
PG_PASSWORD_DEFAULT="$(gen_token)"

echo
echo "${BOLD}管理员后台登录密码（ADMIN_TOKEN）${RESET}"
echo "这是你以后访问 /admin 取数据用的。请妥善保管。"
echo "默认已为你生成强随机值。直接回车采用，或粘贴你自己的："
read -r CUSTOM_ADMIN
ADMIN_TOKEN="${CUSTOM_ADMIN:-$ADMIN_TOKEN_DEFAULT}"

POSTGRES_PASSWORD="${PG_PASSWORD_DEFAULT}"

# --- 4. DeepSeek（可选，V4 默认不调用 LLM） ----------------------------
echo
echo "${BOLD}DeepSeek API（可选）${RESET}"
echo "V4 已把 AI 草稿写死，case 渲染不调用 DeepSeek，所以一般 ${YELLOW}留空即可${RESET}。"
echo "只有你要用 /admin 里的「LLM 生成本次实验总结」功能时才需要 key。"
read -rp "DeepSeek API key（直接回车跳过）: " DEEPSEEK_API_KEY
LLM_PROVIDER="disabled"
if [ -n "${DEEPSEEK_API_KEY}" ]; then
  LLM_PROVIDER="deepseek"
fi

# --- 5. 写 .env -------------------------------------------------------
if [ -f .env ]; then
  TS="$(date +%Y%m%d_%H%M%S)"
  cp .env ".env.bak.${TS}"
  warn "已备份原 .env 到 .env.bak.${TS}"
fi

cat > .env <<EOF
# Generated by deploy/setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT THIS FILE.

SITE_DOMAIN=${SITE_DOMAIN}
ACME_EMAIL=

ADMIN_TOKEN=${ADMIN_TOKEN}
CORS_ORIGINS=["*"]

POSTGRES_USER=medai
POSTGRES_DB=medai
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

LLM_PROVIDER=${LLM_PROVIDER}
LLM_DRY_RUN=false
DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
DEEPSEEK_BASE_URL=https://api.deepseek.com
DEEPSEEK_MODEL=deepseek-chat

BACKUP_INTERVAL_SECONDS=86400
EOF

chmod 600 .env
ok "已写入 .env（权限 600，仅本机可读）"

# --- 5b. 录音存储目录（权限必须对，否则语音上传 500）------------------
# docker-compose.prod.yml 把 ./data/voice_recordings 挂进后端容器。如果这个
# 目录不存在，Docker 会用 root:root 建出来；而后端容器里跑的是 uid 1001 的
# app 用户（见 backend/Dockerfile），写不进去 → 医生点「开始录音」后上传报
# 500。上海服务器就是这么坏的（tarball 迁移时目录被 root 重建）。
# 只 chown 属主 uid 即可，不依赖容器里的 gid。
mkdir -p data/voice_recordings
if chown -R 1001 data/voice_recordings 2>/dev/null || sudo chown -R 1001 data/voice_recordings; then
  ok "录音目录 data/voice_recordings 已就绪（属主 uid 1001，与容器内 app 用户一致）"
else
  warn "无法 chown data/voice_recordings；语音上传可能会失败。请手动执行： sudo chown -R 1001 data/voice_recordings"
fi

# --- 6. 启动 docker compose -------------------------------------------
echo
log "开始 build + 启动 4 个容器：db / backend / frontend / caddy"
log "首次 build 约 3-5 分钟，请耐心等待…"
docker compose -f docker-compose.prod.yml --env-file .env up -d --build

# --- 7. 等服务起来 ----------------------------------------------------
log "等待 backend healthcheck 通过（最多 60 秒）…"
for i in $(seq 1 30); do
  status="$(docker inspect --format '{{.State.Health.Status}}' $(docker compose -f docker-compose.prod.yml ps -q backend) 2>/dev/null || echo unknown)"
  if [ "$status" = "healthy" ]; then
    ok "backend healthy"
    break
  fi
  sleep 2
done

# --- 8. 输出最终结果 --------------------------------------------------
echo
echo "${GREEN}${BOLD}=========================================${RESET}"
echo "${GREEN}${BOLD}  部署完成！${RESET}"
echo "${GREEN}${BOLD}=========================================${RESET}"
echo
echo "🩺  ${BOLD}受试者访问网址${RESET}（发给医生）："
echo "    ${BOLD}https://${SITE_DOMAIN}/${RESET}"
echo
echo "🔐  ${BOLD}管理员后台${RESET}（你写论文取数据用）："
echo "    https://${SITE_DOMAIN}/admin"
echo "    Token: ${BOLD}${ADMIN_TOKEN}${RESET}"
echo
echo "📝  ${BOLD}保存 token 的地方${RESET}：./.env  （文件权限 600）"
echo
echo "⏳  首次访问可能要等 30-60 秒，Caddy 正在向 Let's Encrypt 申请 HTTPS 证书。"
echo "    如果浏览器报「证书错误」，等 1 分钟刷新即可。"
echo
echo "🛠   ${BOLD}查看运行状态${RESET}：       docker compose -f docker-compose.prod.yml ps"
echo "🛠   ${BOLD}查看日志${RESET}：             docker compose -f docker-compose.prod.yml logs -f"
echo "🛠   ${BOLD}手动备份数据库${RESET}：      bash deploy/backup.sh"
echo "🛠   ${BOLD}彻底销毁所有数据${RESET}：    docker compose -f docker-compose.prod.yml down -v"
echo
echo "📖  完整操作手册：${BOLD}deploy/DEPLOY.md${RESET}"
