"""phase 1: initial schema

Revision ID: 2f60ea61eade
Revises: 
Create Date: 2026-04-27 07:56:25.762319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f60ea61eade'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('is_practice', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('defect_present', sa.Boolean(), nullable=False),
    sa.Column('defect_type', sa.String(length=128), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('patient_message', sa.Text(), nullable=False),
    sa.Column('chart_snapshot', sa.JSON(), nullable=False),
    sa.Column('ai_draft', sa.Text(), nullable=False),
    sa.Column('facts_used', sa.JSON(), nullable=False),
    sa.Column('risk_cue', sa.Text(), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('gold_action', sa.String(length=32), nullable=False),
    sa.Column('gold_action_alternates', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cohort_summaries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.Column('order_template_id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=64), nullable=True),
    sa.Column('training_level', sa.String(length=64), nullable=True),
    sa.Column('years_practice', sa.Integer(), nullable=True),
    sa.Column('weekly_message_volume', sa.String(length=32), nullable=True),
    sa.Column('prior_ai_use', sa.String(length=32), nullable=True),
    sa.Column('ai_familiarity', sa.Integer(), nullable=True),
    sa.Column('ai_brands_used', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_template_id'], ['order_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('participant_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_presentations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_presentations_session_order', 'case_presentations', ['session_id', 'order_index'], unique=False)
    op.create_table('post_surveys',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('participant_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('server_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_presentation_id', sa.String(length=64), nullable=False),
    sa.Column('selected_action', sa.String(length=32), nullable=False),
    sa.Column('send_as_is_flag', sa.Boolean(), nullable=False),
    sa.Column('edit_flag', sa.Boolean(), nullable=False),
    sa.Column('discard_flag', sa.Boolean(), nullable=False),
    sa.Column('escalate_flag', sa.Boolean(), nullable=False),
    sa.Column('escalate_subtype', sa.String(length=64), nullable=True),
    sa.Column('final_reply_text', sa.Text(), nullable=False),
    sa.Column('final_reply_char_count', sa.Integer(), nullable=False),
    sa.Column('edit_distance', sa.Integer(), nullable=True),
    sa.Column('client_stats', sa.JSON(), nullable=True),
    sa.Column('server_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_presentation_id'], ['case_presentations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_presentation_id')
    )
    op.create_table('case_surveys',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_presentation_id', sa.String(length=64), nullable=False),
    sa.Column('safe_to_send', sa.Integer(), nullable=False),
    sa.Column('confidence_in_judgment', sa.Integer(), nullable=False),
    sa.Column('ai_draft_helpful', sa.Integer(), nullable=False),
    sa.Column('server_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_presentation_id'], ['case_presentations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_presentation_id')
    )
    op.create_table('ui_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('case_presentation_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('client_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_presentation_id'], ['case_presentations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ui_events_presentation', 'ui_events', ['case_presentation_id'], unique=False)
    op.create_index('ix_ui_events_session_type', 'ui_events', ['session_id', 'event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ui_events_session_type', table_name='ui_events')
    op.drop_index('ix_ui_events_presentation', table_name='ui_events')
    op.drop_table('ui_events')
    op.drop_table('case_surveys')
    op.drop_table('actions')
    op.drop_table('post_surveys')
    op.drop_index('ix_case_presentations_session_order', table_name='case_presentations')
    op.drop_table('case_presentations')
    op.drop_table('sessions')
    op.drop_table('participants')
    op.drop_table('order_templates')
    op.drop_table('llm_calls')
    op.drop_table('cohort_summaries')
    op.drop_table('cases')
    # ### end Alembic commands ###
